### ISSUE TITLE
Amazing and Thank You

### ISSUE THREAD

**Issue by LubuLubu2** [kijai/ComfyUI-DepthAnythingV2#3]
Thank you for this awesome node. one problem i had was the autodownload, it wont download some models from HF, for example fp16 small gives an error and says it doesn't exist.

On a 3060ti with 60% power limit  (it's summer) with fp32large preprocessing and bach size of 88 pictures at 832x1216 resolution it took about 180 second to complete and used 6.8GB v-ram and around 10GB or system memory. quality is just superb. (less than 180s because my SaveImage nod was also doing it's thing)

Wish we had a DepthAnything controlnet model for SDXL but for now MiDaS Depth model works really well with DepthAnything preprocessed images.

Thank you.

**Comment by kijai** [comment]
That's weird, they are all working for me currently, even tried deleting the fp16 small, and it downloads it again.

The very first diffusers SDXL depth controlnet is actually very good in my opinion, probably what you are using. I never liked the DepthAnything ControlNet at all, currently best 1.5 depth controlnet, in my opinion, is the depth++ :
https://huggingface.co/huchenlei/ControlNet_plus_plus_collection_fp16/tree/main

**Comment by LubuLubu2** [comment]
Maybe connection issue was on my part, either way i downloaded them all.
I will check the link, thanks man and great job <3
