### ISSUE TITLE
Add cv2 to requirements.txt

### ISSUE THREAD

**Issue by phenomen** [kijai/ComfyUI-DepthAnythingV2#4]
`cv2` is imported in `util/transform.py` but is not listed in `requirements.txt` resulting in an error:
```
ModuleNotFoundError: No module named 'cv2'
```
I installed `cv2`pip manually and then ComfyUI-DepthAnythingV2 loaded successfully.

**Comment by kijai** [comment]
Yeah I missed that file as it's not actually used at all, cleaned up the code a bit so there's no need to have cv2 anymore for this.
