### ISSUE TITLE
Colors are a bit off compared to original repo, any ideas?

### ISSUE THREAD

**Issue by C0nsumption** [kijai/ComfyUI-DepthAnythingV2#5]
## **This is the colormap from the normal repo:**
![normal](https://github.com/kijai/ComfyUI-DepthAnythingV2/assets/98207055/97453dfb-b790-4d0a-880b-6e32fb85fcec)

Find that when I try the color conversions from Marigold the results are much darker and not as accurate.
Any ideas?

know the original repo uses Spectral_r colormap from matplotlib which seems to be the Spectral from Marigold reversed (its not as simple as inversion but you get me. the blue is where the red is.)
![spetral](https://github.com/kijai/ComfyUI-DepthAnythingV2/assets/98207055/8b31ac01-19e4-4b9c-961c-7428d559e492)

**Comment by kijai** [comment]
the _r at end of colormap means reversed yes, if you invert the depth before the colorize node, the results should be identical.

**Comment by C0nsumption** [comment]
## I had tried that earlier but only after the Colorize depthmap. That's why it didn't work. Worked perfect if placed before.
![ComfyUI_temp_piaup_00003_](https://github.com/kijai/ComfyUI-DepthAnythingV2/assets/98207055/1647b59d-8897-4e2c-94d0-4dc0e58b3626)


Worked like a charm. Thanks KJ
