### ISSUE TITLE
how to change the preprocessor resolution

### ISSUE THREAD

**Issue by AIRILab** [kijai/ComfyUI-DepthAnythingV2#9]
![企业微信截图_17195583732265](https://github.com/kijai/ComfyUI-DepthAnythingV2/assets/171908704/047d0a72-92e8-430e-91ad-e21ce9b3064c)
can I change the preprocessor resolution when I using the depth anything V2?

**Comment by kijai** [comment]
It simply uses the resolution of the input, if you want it lower you can resize the image before this node.
